-- =====================================================================
-- Bootstrap (safe to re-run)
-- =====================================================================
set search_path to public;
create extension if not exists pgcrypto; -- for gen_random_uuid()

-- =====================================================================
-- Menus (counter/partition lives here)
-- NOTE: no default depending on menu_num (Postgres forbids that).
-- We'll set the name via a trigger if it's NULL/blank.
-- =====================================================================
create table if not exists menus (
  menu_num   integer generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

-- Trigger function to auto-name menus when name is missing
create or replace function set_menu_default_name()
returns trigger language plpgsql as $$
begin
  if new.name is null or length(btrim(new.name)) = 0 then
    -- menu_num is already assigned for IDENTITY columns before BEFORE INSERT triggers
    new.name := 'Menu ' || new.menu_num;
  end if;
  return new;
end $$;

-- Create trigger if not exists
do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'trg_set_menu_default_name'
  ) then
    create trigger trg_set_menu_default_name
      before insert on menus
      for each row
      execute function set_menu_default_name();
  end if;
end $$;

-- =====================================================================
-- Workers & Shift Events
-- =====================================================================
create table if not exists workers(
  worker_id  uuid primary key default gen_random_uuid(),
  full_name  text not null,
  phone_e164 text unique not null,
  is_admin   boolean not null default false
);

create table if not exists shift_events(
  id        uuid primary key default gen_random_uuid(),
  worker_id uuid not null references workers(worker_id),
  kind      text not null check (kind in ('start','end')),
  at        timestamptz not null default now()
);

create index if not exists ix_shift_events_worker_at on shift_events(worker_id, at);

-- =====================================================================
-- Menu Nodes (tree), partitioned by menus.menu_num
-- =====================================================================
create table if not exists menu_nodes (
  node_id     uuid primary key default gen_random_uuid(),
  parent_id   uuid null references menu_nodes(node_id) on delete cascade,
  name        text not null check (length(trim(name)) > 0),
  is_leaf     boolean not null,
  price_cents int,
  sort_order  int not null default 0,
  layer       int not null default 0,        -- 0 = root
  menu_num    integer not null references menus(menu_num),
  created_at  timestamptz not null default now()
);

create index if not exists ix_menu_nodes_parent          on menu_nodes(parent_id);
create index if not exists ix_menu_nodes_partition       on menu_nodes(menu_num);
create index if not exists ix_menu_nodes_parent_sort     on menu_nodes(parent_id, sort_order);
create index if not exists ix_menu_nodes_is_leaf         on menu_nodes(is_leaf);

-- Exactly ONE root per menu (layer=0 and parent_id is null)
create unique index if not exists ux_menu_root_one_per_menu
  on menu_nodes(menu_num)
  where layer = 0 and parent_id is null;

-- =====================================================================
-- Optional: ensure at least one menu and its root exist
-- =====================================================================
do $$
declare
  m int;
  root_count int;
begin
  select menu_num into m from menus order by menu_num limit 1;
  if m is null then
    insert into menus(name) values (null); -- trigger sets "Menu <num>"
    select currval(pg_get_serial_sequence('menus','menu_num'))::int into m;
  end if;

  select count(*) into root_count
  from menu_nodes
  where menu_num = m and parent_id is null and layer = 0;

  if root_count = 0 then
    insert into menu_nodes (parent_id, name, is_leaf, price_cents, sort_order, layer, menu_num)
    values (null, 'Root', false, null, 0, 0, m);
  end if;
end $$;
